version: "3.7"
services:

  nginx:
    image: nginx:1.19.5
    networks:
      - django_network
    volumes:
      - django_media:/data/media/
      - django_static:/data/static/
      - /home/purin715/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  django:
    image: test_image:4
    networks:
      - django_network
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD
    volumes:
      - django_media:/home/young_hyun/mediafiles/
      - django_static:/home/young_hyun/staticfiles/

  mariadb:
    image: mariadb:10.5
    networks:
      - django_network
    volumes:
      - django_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER: django
      MARIADB_PASSWORD: password1234
      MARIADB_ROOT_PASSWORD: password1234

networks:
  django_network:

volumes:
  django_media:
  django_static:
  django_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true